/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 adjustableDesk.glb --transform 
Files: adjustableDesk.glb [296.3KB] > adjustableDesk-transformed.glb [65.2KB] (78%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function AdjustableDesk(props) {
  const { nodes, materials } = useGLTF('/adjustableDesk-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube007_Cube008.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('/adjustableDesk-transformed.glb')
