/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 BarCounter.glb --transform 
Files: BarCounter.glb [13.88KB] > BarCounter-transformed.glb [3.22KB] (77%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BarCounter(props) {
  const { nodes, materials } = useGLTF('./BarCounter-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.kitchenBar_2.geometry} material={materials.wood} />
      <mesh geometry={nodes.kitchenBar_2_1.geometry} material={materials.metal} />
      <mesh geometry={nodes.kitchenBar_2_2.geometry} material={materials.woodDark} />
    </group>
  )
}

useGLTF.preload('/BarCounter-transformed.glb')
