/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 bearmofloat.glb --transform 
Files: bearmofloat.glb [118.27KB] > bearmofloat-transformed.glb [31.3KB] (74%)
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Bearmofloat(props) {
  const { nodes, materials, animations } = useGLTF('/bearmofloat-transformed.glb')
  const { actions } = useAnimations(animations)

  useEffect(() => {
    console.log(actions);
    if (actions && actions[0]) {
        console.log("I am here")
        actions[0].play(); 
      }
    }, [actions]);


  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="body" position={[-0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.01, 0.01]}>
          <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.PaletteMaterial001} />
          <group name="ears" position={[0.07, 0.807, -5.66]} scale={[0.284, 0.344, 0.344]}>
            <mesh name="pSphere1" geometry={nodes.pSphere1.geometry} material={materials.PaletteMaterial001} position={[0, -4.685, 0]} />
          </group>
          <group name="eyes" position={[-0.848, -0.436, -4.621]} scale={[0.141, 0.262, 0.262]}>
            <mesh name="emo" geometry={nodes.emo.geometry} material={materials.PaletteMaterial001} position={[0, 1, 1.969]} rotation={[Math.PI / 2, 0, 0]} scale={[0.893, 0.382, 0.382]}>
              <mesh name="pCube10" geometry={nodes.pCube10.geometry} material={materials.PaletteMaterial001} />
            </mesh>
          </group>
          <mesh name="controls" geometry={nodes.controls.geometry} material={materials.PaletteMaterial001} position={[0.206, 0, 0]} scale={[1.26, 1, 1]}>
            <mesh name="pCube15" geometry={nodes.pCube15.geometry} material={materials.PaletteMaterial001} />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bearmofloat-transformed.glb')
