/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 beehiveblue.glb --transform 
Files: beehiveblue.glb [7.82KB] > beehiveblue-transformed.glb [3.32KB] (58%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BeehiveBlue(props) {
  const { nodes, materials } = useGLTF('./beehiveblue-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]} scale={[0.01, 0.01, 0.007]}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Mesh001_2.geometry} material={materials.lambert2} />
      </group>
    </group>
  )
}

useGLTF.preload('/beehiveblue-transformed.glb')
