/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 boxingRing.glb --transform 
Files: boxingRing.glb [169.62KB] > boxingRing-transformed.glb [18.78KB] (89%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BoxingRing(props) {
  const { nodes, materials } = useGLTF('/boxingRing-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group328789628.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('/boxingRing-transformed.glb')
