/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 boxOpen.glb --transform 
Files: boxOpen.glb [14.22KB] > boxOpen-transformed.glb [3.64KB] (74%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BoxOpen(props) {
  const { nodes, materials } = useGLTF('/boxOpen-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.boxOpen_1.geometry} material={materials.woodDark} />
      <mesh geometry={nodes.boxOpen_1_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.boxOpen_1_2.geometry} material={materials.rock} />
    </group>
  )
}

useGLTF.preload('/boxOpen-transformed.glb')
