/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 cardboardBox.glb --transform 
Files: cardboardBox.glb [11.29KB] > cardboardBox-transformed.glb [2.38KB] (79%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CardboardBox(props) {
  const { nodes, materials } = useGLTF('/cardboardBox-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cardboardBoxOpen_2.geometry} material={materials.wood} />
      <mesh geometry={nodes.cardboardBoxOpen_2_1.geometry} material={materials.woodDark} />
    </group>
  )
}

useGLTF.preload('/cardboardBox-transformed.glb')
