/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Catharsis.glb --transform 
Files: Catharsis.glb [180.56KB] > Catharsis-transformed.glb [52.09KB] (71%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Catharsis(props) {
  const { nodes, materials } = useGLTF('/Catharsis-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCone1.geometry} material={materials.PaletteMaterial001} position={[0, -0.053, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.005, 0.005, 0.008]} />
    </group>
  )
}

useGLTF.preload('/Catharsis-transformed.glb')
