/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Champagne.glb --transform 
Files: Champagne.glb [25.78KB] > Champagne-transformed.glb [5.22KB] (80%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Champagne-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bottle_of_Champagne_Circle009.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('/Champagne-transformed.glb')
