/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 coffeeTable.glb --transform 
Files: coffeeTable.glb [18.98KB] > coffeeTable-transformed.glb [2.9KB] (85%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CoffeeTable(props) {
  const { nodes, materials } = useGLTF('/coffeeTable-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat23} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat24} />
    </group>
  )
}

useGLTF.preload('/coffeeTable-transformed.glb')
