/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 desk.glb --transform 
Files: desk.glb [52.98KB] > desk-transformed.glb [4.42KB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Desk(props) {
  const { nodes, materials } = useGLTF('./desk-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group328327309.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1430384365.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1000350481.geometry} material={materials.mat15} />
    </group>
  )
}

useGLTF.preload('/desk-transformed.glb')
