/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Disruptive.glb --transform 
Files: Disruptive.glb [15.49KB] > Disruptive-transformed.glb [2.22KB] (86%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Disruptive(props) {
  const { nodes, materials } = useGLTF('/Disruptive-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCube5.geometry} material={materials.lambert2} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Disruptive-transformed.glb')
