/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 electricGuitar.glb --transform 
Files: electricGuitar.glb [804.38KB] > electricGuitar-transformed.glb [28.38KB] (96%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ElectricGuitar(props) {
  const { nodes, materials } = useGLTF('/electricGuitar-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ElectricGuitar_mesh.geometry} material={materials.lambert2SG} />
    </group>
  )
}

useGLTF.preload('/electricGuitar-transformed.glb')
