/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 FigPlant.gltf --transform 
Files: FigPlant.gltf [1.01MB] > FigPlant-transformed.glb [35.05KB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FigPlant(props) {
  const { nodes, materials } = useGLTF('./FigPlant-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RubberFigPottedPlant_mesh.geometry} material={materials.RubberFigPottedPlant_mat} />
    </group>
  )
}

useGLTF.preload('/FigPlant-transformed.glb')
