/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Fridge.glb --transform 
Files: Fridge.glb [38.56KB] > Fridge-transformed.glb [3.86KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Fridge(props) {
  const { nodes, materials } = useGLTF('/Fridge-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.kitchenFridgeLarge.geometry} material={materials.metalLight} />
      <mesh geometry={nodes.doorLeft.geometry} material={materials.metalMedium} />
    </group>
  )
}

useGLTF.preload('/Fridge-transformed.glb')
