/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 GoldenGod.glb --transform 
Files: GoldenGod.glb [5.85MB] > GoldenGod-transformed.glb [457.38KB] (92%)
Author: Duznot (https://sketchfab.com/duz_vr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/golden-god-a5f06762e40d4bceaa6fbefd0cce279e
Title: Golden God
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GoldenGod(props) {
  const { nodes, materials } = useGLTF('/GoldenGod-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.GoldenGod_Golden_God_0.geometry} material={materials.Golden_God} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/GoldenGod-transformed.glb')
