/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 isaac.glb --transform 
Files: isaac.glb [141.1KB] > isaac-transformed.glb [36.64KB] (74%)
Author: NGResource (https://sketchfab.com/T0MFULP)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isaac-9ec61d883eb04c79981cada6eb300af7
Title: Isaac
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Issac(props) {
  const { nodes, materials } = useGLTF('/isaac-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Isaac} rotation={[Math.PI / 2, 0, 0]} scale={124.165} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Isaac.001']} position={[0, 0.296, 0]} rotation={[Math.PI / 2, 0, 0]} scale={105.267} />
    </group>
  )
}

useGLTF.preload('/isaac-transformed.glb')
