/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 kawaiiArcade.glb --transform 
Files: kawaiiArcade.glb [46.17KB] > kawaiiArcade-transformed.glb [19.57KB] (58%)
Author: biyen_c (https://sketchfab.com/biyen_c)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylised-kawaii-arcade-machine-13117c5da81643eb9b30bf88950dc739
Title: Stylised Kawaii Arcade Machine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function KawaiiArcade(props) {
  const { nodes, materials } = useGLTF('/kawaiiArcade-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.arcade_machine_MAT_arcade_0.geometry} material={materials.MAT_arcade} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/kawaiiArcade-transformed.glb')
