/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 kirbyArcade.glb --transform 
Files: kirbyArcade.glb [2.49MB] > kirbyArcade-transformed.glb [452.33KB] (82%)
Author: Leon Da Kimchi (https://sketchfab.com/dakimchi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kirby-arcade-3dd08eb777bf402d9a8830f852694d0b
Title: Kirby Arcade
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function KirbyArcade(props) {
  const { nodes, materials } = useGLTF('./kirbyArcade-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.initialShadingGroup} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.lambert2SG} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.lambert4SG} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.lambert7SG} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.lambert8SG} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.lambert3SG} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.lambert5SG} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.lambert6SG} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/kirbyArcade-transformed.glb')
