/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 letterBlock.glb --transform 
Files: letterBlock.glb [223.35KB] > letterBlock-transformed.glb [18.84KB] (92%)
Author: holtkamp (https://sketchfab.com/holtkamp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/letter-block-d628bf4c2215423ab717382d20a04c5b
Title: Letter Block
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LetterBlock(props) {
  const { nodes, materials } = useGLTF('./letterBlock-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Edges} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials.Faces} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials.Letters1} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials.Letters2} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_4.geometry} material={materials.Letters3} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/letterBlock-transformed.glb')
