/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 MetalStool1.glb --transform 
Files: MetalStool1.glb [27.96KB] > MetalStool1-transformed.glb [3.32KB] (88%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MetalStool(props) {
  const { nodes, materials } = useGLTF('/MetalStool1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Stool_01_Cube033.geometry} material={materials['455A64']} />
    </group>
  )
}

useGLTF.preload('/MetalStool1-transformed.glb')
