/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ModernRug.glb --transform 
Files: ModernRug.glb [21.06KB] > ModernRug-transformed.glb [3.6KB] (83%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModernRug(props) {
  const { nodes, materials } = useGLTF('./ModernRug-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Modern_rug_Plane004-Mesh'].geometry} material={materials['78909C']} />
      <mesh geometry={nodes['Modern_rug_Plane004-Mesh_1'].geometry} material={materials['455A64']} />
    </group>
  )
}

useGLTF.preload('/ModernRug-transformed.glb')
