/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 mousepad.glb --transform 
Files: mousepad.glb [6.26KB] > mousepad-transformed.glb [1.43KB] (77%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MousePad(props) {
  const { nodes, materials } = useGLTF('/mousepad-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mousepad.geometry} material={materials.Mousepad} scale={[1, 0.013, 1.217]} />
    </group>
  )
}

useGLTF.preload('/mousepad-transformed.glb')
