/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 mouse.glb --transform 
Files: mouse.glb [15.68KB] > mouse-transformed.glb [2.13KB] (86%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mouse(props) {
  const { nodes, materials } = useGLTF('/mouse-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ComputerMouse_mesh.geometry} material={materials.ComputerMouse_mat1} />
    </group>
  )
}

useGLTF.preload('/mouse-transformed.glb')
