/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 PoolTable.glb --transform 
Files: PoolTable.glb [283.52KB] > PoolTable-transformed.glb [33.69KB] (88%)
Author: Digitalis Reality (https://sketchfab.com/digitalisreality)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-pool-table-5b3d3029632a436b9b887aada9c9b131
Title: Low Poly Pool Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PoolTable(props) {
  const { nodes, materials } = useGLTF('/PoolTable-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial004} position={[-2.445, 3.677, -0.451]} scale={0.173} />
    </group>
  )
}

useGLTF.preload('/PoolTable-transformed.glb')
