/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 railing.glb --transform 
Files: railing.glb [17.47KB] > railing-transformed.glb [2.28KB] (87%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Railing(props) {
  const { nodes, materials } = useGLTF('/railing-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group622475369.geometry} material={materials.mat21} />
    </group>
  )
}

useGLTF.preload('/railing-transformed.glb')
