/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 rooms.glb --transform 
Files: rooms.glb [2.09MB] > rooms-transformed.glb [386KB] (82%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Rooms(props) {
  const { nodes, materials } = useGLTF('/rooms-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface1.geometry} material={materials.PaletteMaterial001} position={[-0.133, 0.009, -0.049]} rotation={[Math.PI/2, 0, 0]} scale={[0.041, 0.038, 0.003]} />
      <mesh geometry={nodes.polySurface7.geometry} material={materials.PaletteMaterial002} position={[0.01, 0.009, -0.04]} rotation={[Math.PI/2, 0, 0]} scale={[0.022, 0.038, 0.003]} />
    </group>
  )
}

useGLTF.preload('/rooms-transformed.glb')
