/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 rooms_1.glb --transform 
Files: rooms_1.glb [2.35MB] > rooms_1-transformed.glb [435.66KB] (81%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Rooms_1(props) {
  const { nodes, materials } = useGLTF('/rooms_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface1.geometry} material={materials.PaletteMaterial001} position={[-0.133, 0.009, -0.046]} rotation={[Math.PI / 2, 0, 0]} scale={[0.041, 0.038, 0.003]} />
      <mesh geometry={nodes.polySurface7.geometry} material={materials.PaletteMaterial002} position={[0.01, 0.009, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.022, 0.038, 0.003]} />
    </group>
  )
}

useGLTF.preload('/rooms_1-transformed.glb')
