/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Sink.glb --transform 
Files: Sink.glb [44.62KB] > Sink-transformed.glb [6.39KB] (86%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Sink(props) {
  const { nodes, materials } = useGLTF('./Sink-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.kitchenSink.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('/Sink-transformed.glb')
