/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 stairs.glb --transform 
Files: stairs.glb [45.64KB] > stairs-transformed.glb [4.79KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Stairs(props) {
  const { nodes, materials } = useGLTF('./stairs-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.stairsOpen.geometry} material={materials.woodDark} />
      <mesh geometry={nodes.Group_2.geometry} material={materials.metal} />
      <mesh geometry={nodes.Group_2_1.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/stairs-transformed.glb')
