/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 stair.glb --transform 
Files: stair.glb [32.19KB] > stair-transformed.glb [3.63KB] (89%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Stair(props) {
  const { nodes, materials } = useGLTF('./stair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.379, -0.214, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.431, 1.006, 0.146]}>
        <mesh geometry={nodes.Mesh006.geometry} material={materials['lambert2.002']} />
        <mesh geometry={nodes.Mesh006_1.geometry} material={materials['lambert3.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/stair-transformed.glb')
