/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 TavernShelf.glb --transform 
Files: TavernShelf.glb [8.99KB] > TavernShelf-transformed.glb [2.29KB] (75%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TavernShelf(props) {
  const { nodes, materials } = useGLTF('./TavernShelf-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box001.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box002.geometry} material={materials['02___Default']} />
    </group>
  )
}

useGLTF.preload('/TavernShelf-transformed.glb')
