/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 theorycraft.glb --transform 
Files: theorycraft.glb [11.38KB] > theorycraft-transformed.glb [2.46KB] (78%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TheoryCraft(props) {
  const { nodes, materials } = useGLTF('/theorycraft-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder1.geometry} material={materials.lambert2} position={[0, 0.019, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.105, 0.105, 0.04]} />
    </group>
  )
}

useGLTF.preload('/theorycraft-transformed.glb')
