/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ToyBlocks.glb --transform 
Files: ToyBlocks.glb [52.45KB] > ToyBlocks-transformed.glb [8.98KB] (83%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ToyBlocks(props) {
  const { nodes, materials } = useGLTF('/ToyBlocks-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.D.geometry} material={materials.PaletteMaterial001} position={[0.078, -0.003, 0.021]} rotation={[1.57, 0.002, -0.021]} scale={[0.019, 0.01, 0.01]} />
    </group>
  )
}

useGLTF.preload('/ToyBlocks-transformed.glb')
