/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 boxClosed.glb --transform 
Files: boxClosed.glb [11.24KB] > boxClosed-transformed.glb [2.51KB] (78%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BoxClosed(props) {
  const { nodes, materials } = useGLTF('/boxClosed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.box_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.box_1_1.geometry} material={materials.rock} />
    </group>
  )
}

useGLTF.preload('/boxClosed-transformed.glb')
