/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 gamingChair.glb --transform 
Files: gamingChair.glb [61.67KB] > gamingChair-transformed.glb [8.36KB] (86%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GamingChair(props) {
  const { nodes, materials } = useGLTF('/gamingChair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.Executive} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.Executive__1} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.Executive__2} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.Executive__3} />
    </group>
  )
}

useGLTF.preload('/gamingChair-transformed.glb')
