/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ieShelves.glb --transform 
Files: ieShelves.glb [293.62KB] > ieShelves-transformed.glb [10.98KB] (96%)
Author: Erik Blaho (https://sketchfab.com/blahoerik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kallax-112x147-6603f06d2a43436da2160981f2df6fe2
Title: KALLAX 112x147
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function IeShelves(props) {
  const { nodes, materials } = useGLTF('/ieShelves-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.KALLAX__112x147_KALLAX_MAIN_COLOR_0.geometry} material={materials.KALLAX_MAIN_COLOR} position={[0, 0.75, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.KALLAX__112x147_KALLAX_SCREW_0.geometry} material={materials.KALLAX_SCREW} position={[0, 0.75, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.KALLAX__112x147_KALLAX_SCREW_HOLE_0.geometry} material={materials.KALLAX_SCREW_HOLE} position={[0, 0.75, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/ieShelves-transformed.glb')
