/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 pc.glb --transform 
Files: pc.glb [348.72KB] > pc-transformed.glb [28.46KB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pc(props) {
  const { nodes, materials } = useGLTF('/pc-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh549538436.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.mesh549538436_1.geometry} material={materials.PaletteMaterial002} />
    </group>
  )
}

useGLTF.preload('/pc-transformed.glb')
