/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 switch.glb --transform 
Files: switch.glb [163.79KB] > switch-transformed.glb [18.04KB] (89%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Switch(props) {
  const { nodes, materials } = useGLTF('/switch-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh621928186.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.mesh621928186_1.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('/switch-transformed.glb')
