/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 tvStand.glb --transform 
Files: tvStand.glb [95.46KB] > tvStand-transformed.glb [7.87KB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TvStand(props) {
  const { nodes, materials } = useGLTF('/tvStand-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.Media_Base} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.Media_Base_1} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.Media_Base_2} />
    </group>
  )
}

useGLTF.preload('/tvStand-transformed.glb')
